### ISSUE TITLE
Strange error on execution

### ISSUE THREAD

**Issue by sjcotto** [vinodbukya6/cp-VTryon-plus-Flask-App#4]
Hello, 

noticed some changes required in order to run, 

```
cmd_parse = "python inference.py 
cmd_parse = "python tryon_utils/inference.py 
```

```
cmd_parse = "python test.py
cmd_parse = "python tryon_utils/test.py
```

after this change, i'm receiving an error on the test step.

```
file_person, file_cloth: <FileStorage: 'person.png' ('image/png')> <FileStorage: 'clothe.png' ('image/png')>
filename1, filename2: person.png clothe.png
libpng warning: iCCP: extra compressed data
libpng warning: iCCP: extra compressed data
Saving  data/test/cloth-mask/clothe.png


Constructing DeepLabv3+ model...
Number of classes: 20
Output stride: 16
Number of Input Channels: 3
load model: checkpoints/inference.pth
time used for the multi-scale image inference is :37.24553029998788
/usr/local/lib/python3.7/site-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
Using CPU device
Time Taken in forward pass = 6.0468971729278564
Keypoints - Nose : [(117, 35, 0.7385799)]
Keypoints - Neck : [(94, 76, 0.53160644)]
Keypoints - R-Sho : [(57, 73, 0.48354018)]
Keypoints - R-Elb : [(9, 124, 0.40133688)]
Keypoints - R-Wr : []
Keypoints - L-Sho : [(128, 81, 0.42455107)]
Keypoints - L-Elb : []
Keypoints - L-Wr : []
Keypoints - R-Hip : []
Keypoints - R-Knee : []
Keypoints - R-Ank : []
Keypoints - L-Hip : []
Keypoints - L-Knee : []
Keypoints - L-Ank : []
Keypoints - R-Eye : [(108, 25, 0.7291436)]
Keypoints - L-Eye : [(124, 30, 0.7333242)]
Keypoints - R-Ear : [(90, 25, 0.7433983)]
Keypoints - L-Ear : [(133, 40, 0.17112795)]
Namespace(batch_size=4, checkpoint='checkpoints/GMM/gmm_final.pth', data_list='test_samples_pair.txt', datamode='test', dataroot='data', display_count=1, fine_height=256, fine_width=192, gpu_ids='', grid_size=5, name='GMM', radius=5, result_dir='result', shuffle=False, stage='GMM', tensorboard_dir='tensorboard', workers=4)
Start to test stage: GMM, named: GMM!
initialization method [normal]
initialization method [normal]
Traceback (most recent call last):
  File "tryon_utils/test.py", line 226, in <module>
    main()
  File "tryon_utils/test.py", line 212, in main
    test_gmm(opt, test_loader, model, board)
  File "tryon_utils/test.py", line 84, in test_gmm
    for step, inputs in enumerate(test_loader.data_loader):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/code/tryon_utils/cp_dataset.py", line 150, in __getitem__
    with open(osp.join(self.data_path, 'pose', pose_name), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/test/pose/person.png'
```

I have all the files in the checkpoints folder, here is a screens

![image](https://user-images.githubusercontent.com/3880470/213877305-0879059b-a40f-45f1-932d-1f7e6276688d.png)

**Comment by AyushRajgor** [comment]
please use a .jpg format image. *.png extension conflicts many hardcoded reference of jpg in many files.
